#                                 Python Exercise No: 2 


#                        <font color=red>Subject: Arrays and String in python</font> 

### 1. What is an array? 

Ans : If we have to store 5 integers then it is simple but if we have to store 500 integers we have to create 500 variables,so          it becomes time consuming and sometimes complex.So to avod this we can use function to store these numbers called array.

An array is a data structure that contains a group of elements. Typically these elements are all of the same data type, such    as an integer or string.
   
An array is a data structure that stores a collection of items. Like lists, arrays are ordered, mutable, enclosed in square      brackets, and able to store non-unique items.
     
Array in Python can be created by importing array module. array(data_type, value_list) is used to create an array with data type and value list .Numpy is also used to create an array.
  
To use arrays in Python, you need to import either an array module or a NumPy package.
     
      

In [1]:
import array as arr 
a = arr.array('i', [1, 2, 3]) 
b = arr.array('d', [2.5, 3.2, 3.3]) 

  

### 2. What is difference between array and list?

Ans : Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be         used to store any data type (real numbers, strings, etc).
    
    
> The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown.
     
     
**Following are the differences between lists and arrays in Python:**
  1. Arrays need to be declared. Lists don’t, because they are a part of Python's syntax. This is the reason lists are               more often used than arrays. But in case you want to perform some arithmetic function to your list, one should go               with arrays instead. 
  2. Arrays can store very big data.
  3. Lists cannot directly handle math operations. For example, you can divide each element of an array by the same                   number with just one line of code. If you try the same with a list, you’ll get an error.
  4. Elements are stored consecutively in arrays whereas it is stored randomly in  lists.
  5. Arrays are of fixed size. In contrast, lists are dynamic and flexible and can expand and contract its size.
  6. An array is the data structure that contains a collection of similar type data elements whereas the list is                     considered as non-primitive data structure contains a collection of unordered elements.
           

In [2]:
import numpy as np
array = np.array([3, 6, 9, 12])
division = array/3
print(division)
print (type(division))



[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [3]:
#list = [3, 6, 9, 12]
#division = list/3
#This will give error,because we cannot do operations with list. 

### 3. How to change the shape of an array? 

**Ans :**  Reshaping means changing the shape of an array.

 The shape of an array is the number of elements in each dimension.

 By reshaping we can add or remove dimensions or change number of elements in each dimension.
    
    



In [4]:
a = np.array([1,2,3])
print(a.shape)

(3,)


In [5]:
x = np.array([2,3,4,5,6,7]) 
x    
b= x.reshape(3,2)
print(b)

[[2 3]
 [4 5]
 [6 7]]


### 4. What does the name.strip () do? 

**Ans:** strip() is an inbuilt function in Python programming language that returns a copy of the string with both leading and           trailing characters removed (based on the string argument passed).
**Syntax:**
- string.strip([chars])
- Parameter: 
  There is only one optional parameter in it:
    1. chars - a string specifying the set of characters to be removed. 
- If the optional chars parameter is not given, all leading and trailing whitespaces are removed from the string.
- Return Value:
  Returns a copy of the string with both leading and trailing characters removed.

In [6]:
string = """    red is red    """ 
  
# prints the string without stripping 
print(string)  
  
# prints the string by removing leading and trailing whitespaces 
print(string.strip())    
  
# prints the string by removing geeks 
print(string.strip(" red")) 

    red is red    
red is red
is


### 5. When we use triple single or triple double quotes to define a string? 

**Ans:**  Printing strings on multiple lines can make text more readable to humans. With multiple lines, strings can be grouped          into clean and orderly text, formatted as a letter, or used to maintain the linebreaks of a poem or song lyrics.
         To create strings that span multiple lines, triple single quotes ''' or triple double quotes """ are used to enclose            the string.
         
 With triple quotes, you can print strings on multiple lines to make text, especially lengthy text, easier to read.
Example:


In [7]:
print('''
This string is on
multiple lines
within three single
quotes on either side.
''')



This string is on
multiple lines
within three single
quotes on either side.



In [8]:
print("""
This string is on
multiple lines
within three double
quotes on either side.
""")


This string is on
multiple lines
within three double
quotes on either side.



**Coding Exercise:** 

### 6. Create a character type array? 

**Ans:** 
chr() does the reverse of ord(). Given a numeric value n, chr(n) returns a string representing the character that corresponds to n.




In [9]:
import numpy as np
#b = np.array(['h','e','l','l','o'])
charar = np.chararray((3, 3))
charar

chararray([['', '', ''],
           ['', '', ''],
           ['', '', '']], dtype='|S1')

In [10]:
charar[:] = 'a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

### 7. Create a “hello” string and access the string character "ll" in python? 

In [11]:
# Access  string character "ll"
string="hello"
print(string[2:4])
#print(string[-3:-1])  

ll


### 8. Create an array to get largest and smallest number using minimum and maximum function? 

In [14]:
import array as arr 
array=arr.array('i',[45,20,12,34,20,67,5])
print("Largest no in the array is:" ,max(array))
print("Smallest no in the array is:",min(array))


Largest no in the array is: 67
Smallest no in the array is: 5


### 9. If name is “core python” then access the "python" from name and reverse "python" using slicing? 

In [15]:
name=input()
p=name[5:11]
print(p)
length=len(p)
reverse=p[length::-1]
print(reverse)


core python
python
nohtyp


### 10. Create an array of integer type and add element 12 using append method and remove one element using remove methods? 

In [16]:
import array as ar
arr=ar.array('i',[34,20,19,3,0,7,50])
print("Initial array is:",arr)
arr.append(12)
print("Array after using append method is:",arr)
arr.remove(0)
print("Array after using remove method is:",arr)



Initial array is: array('i', [34, 20, 19, 3, 0, 7, 50])
Array after using append method is: array('i', [34, 20, 19, 3, 0, 7, 50, 12])
Array after using remove method is: array('i', [34, 20, 19, 3, 7, 50, 12])


### 11. Create a single dimensional and 3 dimensional array using numpy? 

In [17]:
import numpy as np
# single dimensional array
array = np.array([4,5,6])
array



array([4, 5, 6])

In [18]:
array_1=np.arange(10, 35, 3)
array_1

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

In [19]:
array_1.shape

(9,)

In [20]:
#2D array
array_2 = np.array([[1,2,3],[4,5,6]])
array_2



array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array_2.shape

(2, 3)

In [22]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
# 3D array
array_3 = np.arange(27).reshape(3,3,3)
array_3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
array_3.shape

(3, 3, 3)

### 12. Create a “Programiz” string and convert the string into upper, lower case? And replace given string by “program” using replace method? 


In [25]:
string="Programiz"
print("Original string:",string)
up=string.upper()
print("String in uppercase:",up)
low=string.lower()
print("String in lowercase:",low)
new=string.replace(string,"program")
print("Replaced string:",new)

Original string: Programiz
String in uppercase: PROGRAMIZ
String in lowercase: programiz
Replaced string: program


### 13. Create a two array one using linspace and another using arange function and then subtract array1 from array 2? 

numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None) : Returns number spaces evenly w.r.t interval. Similar to arange but instead of step it uses sample number.
 
 Parameters :
- start  : [optional] start of interval range. By default start = 0
- stop   : end of interval range
- restep : If True, return (samples, step). By deflut restep = False
- num    : [int, optional] No. of samples to generate
- dtype  : type of output array
 


In [26]:
array1=np.linspace(15,30,num=5)
array2=np.arange(10, 20, 2)
print("Array1 is:",array1)
print("Array1 is:",array2)
output=np.subtract(array1,array2)
print("The output of the array is:",output)

Array1 is: [15.   18.75 22.5  26.25 30.  ]
Array1 is: [10 12 14 16 18]
The output of the array is: [ 5.    6.75  8.5  10.25 12.  ]


In [27]:
arr1=np.array([[2, -4, 5], [-6, 2, 0]]) 
arr2=np.array([[0, -7, 5], [5, -2, 9]])
print("First array is:",arr1)
print("Second array is:",arr2)
output=np.subtract(arr1,arr2)
print("The output of the array is:",output)

First array is: [[ 2 -4  5]
 [-6  2  0]]
Second array is: [[ 0 -7  5]
 [ 5 -2  9]]
The output of the array is: [[  2   3   0]
 [-11   4  -9]]


### 14. Create a “happy new year” string and then separate this string by (space) ",”? 

The split() method splits a string into a list.
You can specify the separator, default separator is any whitespace.

In [28]:
wish= "happy new year"
word=wish.split()
print(word)

['happy', 'new', 'year']


### 15. Create two string and check whether one string present in another string using membership operator? 

A Membership Operator in Python can be defined as being an operator that is used to validate the membership of a value. This operator is used to test memberships in variables such as strings, integers as well as tuples.

In [29]:
str1=["red","yellow","blue","pink"]
str2=["apple","banana","mango","graps"]
for item in str1: 
    if item in str2: 
        print("Present")     
else: 
    print("not present")

not present


In [30]:
str1=["red","yellow","blue","pink"]
str2=["apple","banana","mango","red"]
for item in str1: 
    if item in str2: 
        print("Present")     
else: 
    print("not present")

Present
not present
