In [1]:
import imblearn

In [2]:
import numpy as np
import pandas as pd


In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris[["species"]]=iris["species"].replace(to_replace={'setosa':0,'versicolor':1,'virginica':2})
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [5]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
X_data = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']] # first two features only
y_labels = iris['species']
print(X_data.shape)
print(y_labels.shape)

(150, 4)
(150,)


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_data,y_labels,test_size=0.2,train_size=0.8,random_state=100)

In [8]:
print("before oversampling count of label '0' : {}".format(sum(y_train == 0)))
print("before oversampling count of label '1' : {}".format(sum(y_train == 1)))
print("before oversampling count of label '2' : {}".format(sum(y_train == 2)))


before oversampling count of label '0' : 39
before oversampling count of label '1' : 44
before oversampling count of label '2' : 37


In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report



In [10]:
from imblearn import under_sampling, over_sampling
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss


In [11]:
import sklearn

In [12]:

from sklearn.naive_bayes import GaussianNB 
gnb1= GaussianNB()
gnb1.fit(x_train,y_train)
y_pred1 = gnb1.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred1)
print(cm)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred1)
print("Accuracy of Naive bayes classifier is :",accuracy)

[[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]
Accuracy of Naive bayes classifier is : 0.9666666666666667


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.83      0.91         6
           2       0.93      1.00      0.96        13

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



## Oversampling - SMOTE


In [15]:
from imblearn.over_sampling import SMOTE
smt = SMOTE()
x_train_s,y_train_s = smt.fit_sample(x_train,y_train)

In [16]:
print("after oversampling count of label '0' : {}".format(sum(y_train_s == 0)))
print("after oversampling count of label '1' : {}".format(sum(y_train_s == 1)))
print("after oversampling count of label '2' : {}".format(sum(y_train_s == 2)))


after oversampling count of label '0' : 44
after oversampling count of label '1' : 44
after oversampling count of label '2' : 44


In [17]:
from sklearn.naive_bayes import GaussianNB
gnb2= GaussianNB()
gnb2.fit(x_train_s,y_train_s)
y_pred2 = gnb2.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred2)
print(cm)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred2)
print("Accuracy of Naive bayes classifier is :",accuracy)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

[[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]
Accuracy of Naive bayes classifier is : 0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.83      0.91         6
           2       0.93      1.00      0.96        13

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



## NearMiss - Undersampling


In [19]:
from imblearn.under_sampling import NearMiss
nr= NearMiss()

x_train_miss,y_train_miss = nr.fit_sample(x_train,y_train.ravel())

In [20]:
print("after undersampling count of label '0' : {}".format(sum(y_train_miss == 0)))
print("after undersampling count of label '1' : {}".format(sum(y_train_miss == 1)))
print("after undersampling count of label '2' : {}".format(sum(y_train_miss == 2)))


after undersampling count of label '0' : 37
after undersampling count of label '1' : 37
after undersampling count of label '2' : 37


In [21]:
from sklearn.naive_bayes import GaussianNB
gnb3= GaussianNB()
gnb3.fit(x_train_miss,y_train_miss)
y_pred3 = gnb3.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred3)
print(cm)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred3)
print("Accuracy of Naive bayes classifier is :",accuracy)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred3))


[[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]
Accuracy of Naive bayes classifier is : 0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.83      0.91         6
           2       0.93      1.00      0.96        13

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30

